"""add is_active and token_count to chat_sessions

Revision ID: c44159d0aecb
Revises: 
Create Date: 2026-05-24 14:53:42.899984

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c44159d0aecb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_sessions', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('chat_sessions', sa.Column('token_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_sessions', 'token_count')
    op.drop_column('chat_sessions', 'is_active')
    # ### end Alembic commands ###
